### ISSUE TITLE
use vue sfc to render page, very slow, why?

### ISSUE THREAD

**Issue by bluemsn** [chrisvfritz/vue-render-performance-comparisons#2]
use sfc  to render this page, but very slow, about 500 ~ 600ms 

```
Fastest: 608ms
Median: 665ms
Average: 705.8ms
95th Perc.: undefinedms
Slowest: 918ms
```

At first, I wanted to test the rendering performance of nested components in complex scenes, but now it's very slow to render in a simple nested component
and i can't set `maxCount  = 100`  , because chrome will be crash 

![image](https://cloud.githubusercontent.com/assets/3715420/18953839/e2838c26-8682-11e6-9527-2363277f5802.png)

**Comment by chrisvfritz** [comment]
It's slower because full components are the wrong tool for this extreme use case (rendering a list of 10,000 items). For each normal component, Vue does setup for the reactivity system, which is unnecessary just to render <li>hi</li>. You can also see the speed increase drastically by just rendering each <li> directly in the list component, instead of in its own component.
